### PR TITLE
Serve a default page when no hostname is configured.

### PR DESCRIPTION
**Pull request by mjallday**
Redirect acme-challenge to a well known location

1. Provide a default redirect when someone requests the site and there's no host configured. This should give a more consistent experience if people do not support SNI.
1. Redirect `/.well-known/acme-challenge/` to a well known server for confirmation.

### CODE REVIEW

**Comment by mjallday** [comment]
@adubeniuk i think we can use something like this for https://getverygood.slack.com/archives/D51JYHWAG/p1494885695280632

> vault.customer.com > CNAME > sandbox.verygoodproxy.com > terminator nginx > tenant.sandbox.verygoodproxy.com
to validate that domain name we need curl -kL https://vault.customer.com/.well-known/acme-challenge/ to return the challenge
I think we can do that on our side and don't bother customers with DNS TXT

This will still mean we will need to ask them to setup DNS but it's less work than the txt entry.

**Comment by mjallday** [comment]
In order for this to work we need to generate a certificate with the host names `sandbox|live.verygoodproxy.com` which is located at `<citadel-bucket>/ssl.verygoodproxy.cert`

**Comment by mjallday** [comment]
@adubeniuk i've confirmed this will work as expected.

we need to provision a service in the genpop environment that will listen at `https://certificates.verygoodsecurity.com/.well-known/acme-challenge/` 

if you look at the nginx config you'll see that we append a header with the original hostname so we should be able to tell which domain name confirmation we want to serve for the request.

**Comment by mjallday** [comment]
@akhon update infra-vault to use 1d68d21 on the pci branch for the terminator stacks. this is good to go!

**Comment by akhon** [comment]
relates to https://github.com/verygood-ops/infra-vault/issues/449

**Pull request merged**
