### PR TITLE
Route SFTP traffic to sftp app

### PR DESCRIPTION
**Pull request by k-sever**
## Fixes https://app.clubhouse.io/vgs/story/51634/update-terminators-to-split-traffic-between-sftp-http

### CODE REVIEW

**Comment by k-sever** [comment]
[ch51634]

**Comment by k-sever** [comment]
Pls make sure lendup env also has SFTP app and respective cnames before applying it to LU stack

**Comment by k-sever** [comment]
@mjallday this looks like a high risk change. what's the migration plan here?

Why do you think it's a high risk? To me it looks like an internal DNS mapping stuff, am I missing smth?

I've tested that on dev already.
I suggest we roll that out on sandbox first, then do the same for live in a week.
Just need to get a ping on when it happens for sandbox, so that we could observe with high attention the sftp metrics

**Comment by mjallday** [comment]
High risk in that if it goes wrong all our live or sandbox customers are impacted. 

We need to have a good rollback strategy that we can execute with the smallest possible ttl. 

Testing in dev is great, but if there is a mistake in prod it will still impact live and sandbox traffic so there needs to be a clear rollback strategy.

**Comment by zdmytriv** [comment]
closing in favor of https://github.com/verygood-ops/nginx-ssl-router/pull/75

**Pull request closed without merging**
