### PR TITLE
Allow port 80 for custom configs

### PR DESCRIPTION
**Pull request by zdmytriv**
screen shot 2018-11-21 at 3 39 48 pm

### CODE REVIEW

**Comment by max-lobur** [comment]
Screenshot is from cloudflare?
how do they ensure that connection goes to the correct backend without ssl

**Comment by zdmytriv** [comment]
That is bad idea

**Comment by zdmytriv** [comment]
Actually idea is OK, reopened

**Comment by max-lobur** [comment]
LOL
@zdmytriv see my comment^

**Comment by zdmytriv** [comment]
I thought that on ELB we have 443 -> 80 but we actually have 80 -> 80

screen shot 2018-11-21 at 5 06 28 pm

Closing again.

**Pull request closed without merging**
